package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/spiegela/gorackhd/client/api_2_0"
)

// Default rackhd HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new rackhd HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Rackhd {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("localhost", "/api/2.0", []string{"https", "http"})
	return New(transport, formats)
}

// New creates a new rackhd client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Rackhd {
	cli := new(Rackhd)
	cli.Transport = transport

	cli.API20 = api_2_0.New(transport, formats)

	return cli
}

// Rackhd is a client for rackhd
type Rackhd struct {
	API20 *api_2_0.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Rackhd) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.API20.SetTransport(transport)

}
