package catalogs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCatalogsGetParams creates a new CatalogsGetParams object
// with the default values initialized.
func NewCatalogsGetParams() *CatalogsGetParams {
	var ()
	return &CatalogsGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCatalogsGetParamsWithTimeout creates a new CatalogsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCatalogsGetParamsWithTimeout(timeout time.Duration) *CatalogsGetParams {
	var ()
	return &CatalogsGetParams{

		timeout: timeout,
	}
}

/*CatalogsGetParams contains all the parameters to send to the API endpoint
for the catalogs get operation typically these are written to a http.Request
*/
type CatalogsGetParams struct {

	/*Query
	  A query string containing catalog properties to search

	*/
	Query *string
	/*Sort
	  Query string specifying properties to sort with

	*/
	Sort *string

	timeout time.Duration
}

// WithQuery adds the query to the catalogs get params
func (o *CatalogsGetParams) WithQuery(query *string) *CatalogsGetParams {
	o.Query = query
	return o
}

// WithSort adds the sort to the catalogs get params
func (o *CatalogsGetParams) WithSort(sort *string) *CatalogsGetParams {
	o.Sort = sort
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CatalogsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Query != nil {

		// query param query
		var qrQuery string
		if o.Query != nil {
			qrQuery = *o.Query
		}
		qQuery := qrQuery
		if qQuery != "" {
			if err := r.SetQueryParam("query", qQuery); err != nil {
				return err
			}
		}

	}

	if o.Sort != nil {

		// query param sort
		var qrSort string
		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {
			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
