package workflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWorkflowsInstanceIDParams creates a new GetWorkflowsInstanceIDParams object
// with the default values initialized.
func NewGetWorkflowsInstanceIDParams() *GetWorkflowsInstanceIDParams {
	var ()
	return &GetWorkflowsInstanceIDParams{}
}

/*GetWorkflowsInstanceIDParams contains all the parameters to send to the API endpoint
for the get workflows instance ID operation typically these are written to a http.Request
*/
type GetWorkflowsInstanceIDParams struct {

	/*InstanceID*/
	InstanceID string
}

// WithInstanceID adds the instanceId to the get workflows instance ID params
func (o *GetWorkflowsInstanceIDParams) WithInstanceID(InstanceID string) *GetWorkflowsInstanceIDParams {
	o.InstanceID = InstanceID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkflowsInstanceIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param instanceId
	if err := r.SetPathParam("instanceId", o.InstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
