package workflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/emccode/gorackhd/models"
)

// GetWorkflowsLibraryReader is a Reader for the GetWorkflowsLibrary structure.
type GetWorkflowsLibraryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetWorkflowsLibraryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetWorkflowsLibraryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetWorkflowsLibraryDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetWorkflowsLibraryOK creates a GetWorkflowsLibraryOK with default headers values
func NewGetWorkflowsLibraryOK() *GetWorkflowsLibraryOK {
	return &GetWorkflowsLibraryOK{}
}

/*GetWorkflowsLibraryOK handles this case with default header values.

List all workflows available to run

*/
type GetWorkflowsLibraryOK struct {
	Payload GetWorkflowsLibraryOKBodyBody
}

func (o *GetWorkflowsLibraryOK) Error() string {
	return fmt.Sprintf("[GET /workflows/library][%d] getWorkflowsLibraryOK  %+v", 200, o.Payload)
}

func (o *GetWorkflowsLibraryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetWorkflowsLibraryDefault creates a GetWorkflowsLibraryDefault with default headers values
func NewGetWorkflowsLibraryDefault(code int) *GetWorkflowsLibraryDefault {
	return &GetWorkflowsLibraryDefault{
		_statusCode: code,
	}
}

/*GetWorkflowsLibraryDefault handles this case with default header values.

Unexpected error
*/
type GetWorkflowsLibraryDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get workflows library default response
func (o *GetWorkflowsLibraryDefault) Code() int {
	return o._statusCode
}

func (o *GetWorkflowsLibraryDefault) Error() string {
	return fmt.Sprintf("[GET /workflows/library][%d] GetWorkflowsLibrary default  %+v", o._statusCode, o.Payload)
}

func (o *GetWorkflowsLibraryDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetWorkflowsLibraryOKBodyBody get workflows library o k body body

swagger:model GetWorkflowsLibraryOKBodyBody
*/
type GetWorkflowsLibraryOKBodyBody interface{}
