package workflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostWorkflowsParams creates a new PostWorkflowsParams object
// with the default values initialized.
func NewPostWorkflowsParams() *PostWorkflowsParams {
	var ()
	return &PostWorkflowsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostWorkflowsParamsWithTimeout creates a new PostWorkflowsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostWorkflowsParamsWithTimeout(timeout time.Duration) *PostWorkflowsParams {
	var ()
	return &PostWorkflowsParams{

		timeout: timeout,
	}
}

/*PostWorkflowsParams contains all the parameters to send to the API endpoint
for the post workflows operation typically these are written to a http.Request
*/
type PostWorkflowsParams struct {

	/*Body*/
	Body interface{}
	/*Name
	  The injectable Graph name


	*/
	Name string

	timeout time.Duration
}

// WithBody adds the body to the post workflows params
func (o *PostWorkflowsParams) WithBody(body interface{}) *PostWorkflowsParams {
	o.Body = body
	return o
}

// WithName adds the name to the post workflows params
func (o *PostWorkflowsParams) WithName(name string) *PostWorkflowsParams {
	o.Name = name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PostWorkflowsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// query param name
	qrName := o.Name
	qName := qrName
	if qName != "" {
		if err := r.SetQueryParam("name", qName); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
