package workflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutWorkflowsTasksParams creates a new PutWorkflowsTasksParams object
// with the default values initialized.
func NewPutWorkflowsTasksParams() *PutWorkflowsTasksParams {
	var ()
	return &PutWorkflowsTasksParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutWorkflowsTasksParamsWithTimeout creates a new PutWorkflowsTasksParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutWorkflowsTasksParamsWithTimeout(timeout time.Duration) *PutWorkflowsTasksParams {
	var ()
	return &PutWorkflowsTasksParams{

		timeout: timeout,
	}
}

/*PutWorkflowsTasksParams contains all the parameters to send to the API endpoint
for the put workflows tasks operation typically these are written to a http.Request
*/
type PutWorkflowsTasksParams struct {

	/*Body*/
	Body interface{}

	timeout time.Duration
}

// WithBody adds the body to the put workflows tasks params
func (o *PutWorkflowsTasksParams) WithBody(body interface{}) *PutWorkflowsTasksParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PutWorkflowsTasksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
