package workflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/emccode/gorackhd/models"
)

type PutWorkflowsTasksReader struct {
	formats strfmt.Registry
}

func (o *PutWorkflowsTasksReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutWorkflowsTasksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewPutWorkflowsTasksInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPutWorkflowsTasksDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPutWorkflowsTasksOK creates a PutWorkflowsTasksOK with default headers values
func NewPutWorkflowsTasksOK() *PutWorkflowsTasksOK {
	return &PutWorkflowsTasksOK{}
}

/*PutWorkflowsTasksOK

Add tasks to task library

*/
type PutWorkflowsTasksOK struct {
	Payload PutWorkflowsTasksOKBodyBody
}

func (o *PutWorkflowsTasksOK) Error() string {
	return fmt.Sprintf("[PUT /workflows/tasks][%d] putWorkflowsTasksOK  %+v", 200, o.Payload)
}

func (o *PutWorkflowsTasksOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPutWorkflowsTasksInternalServerError creates a PutWorkflowsTasksInternalServerError with default headers values
func NewPutWorkflowsTasksInternalServerError() *PutWorkflowsTasksInternalServerError {
	return &PutWorkflowsTasksInternalServerError{}
}

/*PutWorkflowsTasksInternalServerError

Error problem was encountered, task was not written.

*/
type PutWorkflowsTasksInternalServerError struct {
	Payload *models.Error
}

func (o *PutWorkflowsTasksInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /workflows/tasks][%d] putWorkflowsTasksInternalServerError  %+v", 500, o.Payload)
}

func (o *PutWorkflowsTasksInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPutWorkflowsTasksDefault creates a PutWorkflowsTasksDefault with default headers values
func NewPutWorkflowsTasksDefault(code int) *PutWorkflowsTasksDefault {
	return &PutWorkflowsTasksDefault{
		_statusCode: code,
	}
}

/*PutWorkflowsTasksDefault

Upload failed
*/
type PutWorkflowsTasksDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the put workflows tasks default response
func (o *PutWorkflowsTasksDefault) Code() int {
	return o._statusCode
}

func (o *PutWorkflowsTasksDefault) Error() string {
	return fmt.Sprintf("[PUT /workflows/tasks][%d] PutWorkflowsTasks default  %+v", o._statusCode, o.Payload)
}

func (o *PutWorkflowsTasksDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

/*PutWorkflowsTasksOKBodyBody PutWorkflowsTasksOKBodyBody put workflows tasks o k body body

swagger:model PutWorkflowsTasksOKBodyBody
*/
type PutWorkflowsTasksOKBodyBody interface{}
