package get

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewGetDhcpLeaseMacParams creates a new GetDhcpLeaseMacParams object
// with the default values initialized.
func NewGetDhcpLeaseMacParams() *GetDhcpLeaseMacParams {
	return &GetDhcpLeaseMacParams{}
}

/*GetDhcpLeaseMacParams contains all the parameters to send to the API endpoint
for the get dhcp lease mac operation typically these are written to a http.Request
*/
type GetDhcpLeaseMacParams struct {

	/*Mac
	  identifier of a mac address

	*/
	Mac string
}

// WithMac adds the mac to the get dhcp lease mac params
func (o *GetDhcpLeaseMacParams) WithMac(mac string) *GetDhcpLeaseMacParams {
	o.Mac = mac
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetDhcpLeaseMacParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param mac
	if err := r.SetPathParam("mac", o.Mac); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
