package get

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/emccode/gorackhd/models"
)

// GetCatalogsReader is a Reader for the GetCatalogs structure.
type GetCatalogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetCatalogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCatalogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetCatalogsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetCatalogsOK creates a GetCatalogsOK with default headers values
func NewGetCatalogsOK() *GetCatalogsOK {
	return &GetCatalogsOK{}
}

/*GetCatalogsOK handles this case with default header values.

An array of catalogs
*/
type GetCatalogsOK struct {
	Payload []*models.Catalog
}

func (o *GetCatalogsOK) Error() string {
	return fmt.Sprintf("[GET /catalogs][%d] getCatalogsOK  %+v", 200, o.Payload)
}

func (o *GetCatalogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCatalogsDefault creates a GetCatalogsDefault with default headers values
func NewGetCatalogsDefault(code int) *GetCatalogsDefault {
	return &GetCatalogsDefault{
		_statusCode: code,
	}
}

/*GetCatalogsDefault handles this case with default header values.

Unexpected error
*/
type GetCatalogsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get catalogs default response
func (o *GetCatalogsDefault) Code() int {
	return o._statusCode
}

func (o *GetCatalogsDefault) Error() string {
	return fmt.Sprintf("[GET /catalogs][%d] GetCatalogs default  %+v", o._statusCode, o.Payload)
}

func (o *GetCatalogsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
