package get

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/emccode/gorackhd/models"
)

type GetCatalogsIdentifierReader struct {
	formats strfmt.Registry
}

func (o *GetCatalogsIdentifierReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCatalogsIdentifierOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetCatalogsIdentifierDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetCatalogsIdentifierOK creates a GetCatalogsIdentifierOK with default headers values
func NewGetCatalogsIdentifierOK() *GetCatalogsIdentifierOK {
	return &GetCatalogsIdentifierOK{}
}

/*GetCatalogsIdentifierOK

A single catalog
*/
type GetCatalogsIdentifierOK struct {
	Payload []*models.Catalog
}

func (o *GetCatalogsIdentifierOK) Error() string {
	return fmt.Sprintf("[GET /catalogs/{identifier}][%d] getCatalogsIdentifierOK  %+v", 200, o.Payload)
}

func (o *GetCatalogsIdentifierOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil {
		return err
	}

	return nil
}

// NewGetCatalogsIdentifierDefault creates a GetCatalogsIdentifierDefault with default headers values
func NewGetCatalogsIdentifierDefault(code int) *GetCatalogsIdentifierDefault {
	return &GetCatalogsIdentifierDefault{
		_statusCode: code,
	}
}

/*GetCatalogsIdentifierDefault

NotFound error
*/
type GetCatalogsIdentifierDefault struct {
	_statusCode int
}

// Code gets the status code for the get catalogs identifier default response
func (o *GetCatalogsIdentifierDefault) Code() int {
	return o._statusCode
}

func (o *GetCatalogsIdentifierDefault) Error() string {
	return fmt.Sprintf("[GET /catalogs/{identifier}][%d] GetCatalogsIdentifier default ", o._statusCode)
}

func (o *GetCatalogsIdentifierDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
