package get

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewGetObmsLibraryIdentifierParams creates a new GetObmsLibraryIdentifierParams object
// with the default values initialized.
func NewGetObmsLibraryIdentifierParams() *GetObmsLibraryIdentifierParams {
	return &GetObmsLibraryIdentifierParams{}
}

/*GetObmsLibraryIdentifierParams contains all the parameters to send to the API endpoint
for the get obms library identifier operation typically these are written to a http.Request
*/
type GetObmsLibraryIdentifierParams struct {

	/*Identifier
	  The obm service name.


	*/
	Identifier string
}

// WithIdentifier adds the identifier to the get obms library identifier params
func (o *GetObmsLibraryIdentifierParams) WithIdentifier(identifier string) *GetObmsLibraryIdentifierParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetObmsLibraryIdentifierParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
