package get

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNodesIdentifierTagsParams creates a new GetNodesIdentifierTagsParams object
// with the default values initialized.
func NewGetNodesIdentifierTagsParams() *GetNodesIdentifierTagsParams {
	var ()
	return &GetNodesIdentifierTagsParams{}
}

/*GetNodesIdentifierTagsParams contains all the parameters to send to the API endpoint
for the get nodes identifier tags operation typically these are written to a http.Request
*/
type GetNodesIdentifierTagsParams struct {

	/*Identifier
	  Mac addresses and unique aliases to identify the node by


	*/
	Identifier string
}

// WithIdentifier adds the identifier to the get nodes identifier tags params
func (o *GetNodesIdentifierTagsParams) WithIdentifier(Identifier string) *GetNodesIdentifierTagsParams {
	o.Identifier = Identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetNodesIdentifierTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
