package get

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/emccode/gorackhd/models"
)

// GetWorkflowsInstanceIDReader is a Reader for the GetWorkflowsInstanceID structure.
type GetWorkflowsInstanceIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetWorkflowsInstanceIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetWorkflowsInstanceIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetWorkflowsInstanceIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetWorkflowsInstanceIDOK creates a GetWorkflowsInstanceIDOK with default headers values
func NewGetWorkflowsInstanceIDOK() *GetWorkflowsInstanceIDOK {
	return &GetWorkflowsInstanceIDOK{}
}

/*GetWorkflowsInstanceIDOK handles this case with default header values.

Fetch workflows

*/
type GetWorkflowsInstanceIDOK struct {
	Payload GetWorkflowsInstanceIDOKBodyBody
}

func (o *GetWorkflowsInstanceIDOK) Error() string {
	return fmt.Sprintf("[GET /workflows/{instanceId}][%d] getWorkflowsInstanceIdOK  %+v", 200, o.Payload)
}

func (o *GetWorkflowsInstanceIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetWorkflowsInstanceIDDefault creates a GetWorkflowsInstanceIDDefault with default headers values
func NewGetWorkflowsInstanceIDDefault(code int) *GetWorkflowsInstanceIDDefault {
	return &GetWorkflowsInstanceIDDefault{
		_statusCode: code,
	}
}

/*GetWorkflowsInstanceIDDefault handles this case with default header values.

Unexpected error
*/
type GetWorkflowsInstanceIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get workflows instance ID default response
func (o *GetWorkflowsInstanceIDDefault) Code() int {
	return o._statusCode
}

func (o *GetWorkflowsInstanceIDDefault) Error() string {
	return fmt.Sprintf("[GET /workflows/{instanceId}][%d] GetWorkflowsInstanceID default  %+v", o._statusCode, o.Payload)
}

func (o *GetWorkflowsInstanceIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetWorkflowsInstanceIDOKBodyBody get workflows instance ID o k body body

swagger:model GetWorkflowsInstanceIDOKBodyBody
*/
type GetWorkflowsInstanceIDOKBodyBody interface{}
