package get

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWorkflowsInstanceIDParams creates a new GetWorkflowsInstanceIDParams object
// with the default values initialized.
func NewGetWorkflowsInstanceIDParams() *GetWorkflowsInstanceIDParams {
	var ()
	return &GetWorkflowsInstanceIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWorkflowsInstanceIDParamsWithTimeout creates a new GetWorkflowsInstanceIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWorkflowsInstanceIDParamsWithTimeout(timeout time.Duration) *GetWorkflowsInstanceIDParams {
	var ()
	return &GetWorkflowsInstanceIDParams{

		timeout: timeout,
	}
}

/*GetWorkflowsInstanceIDParams contains all the parameters to send to the API endpoint
for the get workflows instance ID operation typically these are written to a http.Request
*/
type GetWorkflowsInstanceIDParams struct {

	/*InstanceID*/
	InstanceID string

	timeout time.Duration
}

// WithInstanceID adds the instanceID to the get workflows instance ID params
func (o *GetWorkflowsInstanceIDParams) WithInstanceID(instanceID string) *GetWorkflowsInstanceIDParams {
	o.InstanceID = instanceID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkflowsInstanceIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param instanceId
	if err := r.SetPathParam("instanceId", o.InstanceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
