package get

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDhcpLeaseMacParams creates a new GetDhcpLeaseMacParams object
// with the default values initialized.
func NewGetDhcpLeaseMacParams() *GetDhcpLeaseMacParams {
	var ()
	return &GetDhcpLeaseMacParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDhcpLeaseMacParamsWithTimeout creates a new GetDhcpLeaseMacParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDhcpLeaseMacParamsWithTimeout(timeout time.Duration) *GetDhcpLeaseMacParams {
	var ()
	return &GetDhcpLeaseMacParams{

		timeout: timeout,
	}
}

/*GetDhcpLeaseMacParams contains all the parameters to send to the API endpoint
for the get dhcp lease mac operation typically these are written to a http.Request
*/
type GetDhcpLeaseMacParams struct {

	/*Mac
	  identifier of a mac address

	*/
	Mac string

	timeout time.Duration
}

// WithMac adds the mac to the get dhcp lease mac params
func (o *GetDhcpLeaseMacParams) WithMac(mac string) *GetDhcpLeaseMacParams {
	o.Mac = mac
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetDhcpLeaseMacParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param mac
	if err := r.SetPathParam("mac", o.Mac); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
