package files

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/emccode/gorackhd/models"
)

// PutFilesFileidentifierReader is a Reader for the PutFilesFileidentifier structure.
type PutFilesFileidentifierReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PutFilesFileidentifierReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutFilesFileidentifierOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 201:
		result := NewPutFilesFileidentifierCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewPutFilesFileidentifierInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewPutFilesFileidentifierDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPutFilesFileidentifierOK creates a PutFilesFileidentifierOK with default headers values
func NewPutFilesFileidentifierOK() *PutFilesFileidentifierOK {
	return &PutFilesFileidentifierOK{}
}

/*PutFilesFileidentifierOK handles this case with default header values.

The file was stored
*/
type PutFilesFileidentifierOK struct {
	Payload PutFilesFileidentifierOKBodyBody
}

func (o *PutFilesFileidentifierOK) Error() string {
	return fmt.Sprintf("[PUT /files/{fileidentifier}][%d] putFilesFileidentifierOK  %+v", 200, o.Payload)
}

func (o *PutFilesFileidentifierOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutFilesFileidentifierCreated creates a PutFilesFileidentifierCreated with default headers values
func NewPutFilesFileidentifierCreated() *PutFilesFileidentifierCreated {
	return &PutFilesFileidentifierCreated{}
}

/*PutFilesFileidentifierCreated handles this case with default header values.

Ready.
*/
type PutFilesFileidentifierCreated struct {
	Payload string
}

func (o *PutFilesFileidentifierCreated) Error() string {
	return fmt.Sprintf("[PUT /files/{fileidentifier}][%d] putFilesFileidentifierCreated  %+v", 201, o.Payload)
}

func (o *PutFilesFileidentifierCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutFilesFileidentifierInternalServerError creates a PutFilesFileidentifierInternalServerError with default headers values
func NewPutFilesFileidentifierInternalServerError() *PutFilesFileidentifierInternalServerError {
	return &PutFilesFileidentifierInternalServerError{}
}

/*PutFilesFileidentifierInternalServerError handles this case with default header values.

Failure serving file request.
*/
type PutFilesFileidentifierInternalServerError struct {
	Payload *models.Error
}

func (o *PutFilesFileidentifierInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /files/{fileidentifier}][%d] putFilesFileidentifierInternalServerError  %+v", 500, o.Payload)
}

func (o *PutFilesFileidentifierInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutFilesFileidentifierDefault creates a PutFilesFileidentifierDefault with default headers values
func NewPutFilesFileidentifierDefault(code int) *PutFilesFileidentifierDefault {
	return &PutFilesFileidentifierDefault{
		_statusCode: code,
	}
}

/*PutFilesFileidentifierDefault handles this case with default header values.

Unexpected error
*/
type PutFilesFileidentifierDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the put files fileidentifier default response
func (o *PutFilesFileidentifierDefault) Code() int {
	return o._statusCode
}

func (o *PutFilesFileidentifierDefault) Error() string {
	return fmt.Sprintf("[PUT /files/{fileidentifier}][%d] PutFilesFileidentifier default  %+v", o._statusCode, o.Payload)
}

func (o *PutFilesFileidentifierDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PutFilesFileidentifierOKBodyBody put files fileidentifier o k body body

swagger:model PutFilesFileidentifierOKBodyBody
*/
type PutFilesFileidentifierOKBodyBody interface{}
