package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/emccode/gorackhd/models"
)

// GetSkusIdentifierNodesReader is a Reader for the GetSkusIdentifierNodes structure.
type GetSkusIdentifierNodesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetSkusIdentifierNodesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSkusIdentifierNodesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetSkusIdentifierNodesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetSkusIdentifierNodesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetSkusIdentifierNodesOK creates a GetSkusIdentifierNodesOK with default headers values
func NewGetSkusIdentifierNodesOK() *GetSkusIdentifierNodesOK {
	return &GetSkusIdentifierNodesOK{}
}

/*GetSkusIdentifierNodesOK handles this case with default header values.

return nodes associated with that sku

*/
type GetSkusIdentifierNodesOK struct {
	Payload GetSkusIdentifierNodesOKBodyBody
}

func (o *GetSkusIdentifierNodesOK) Error() string {
	return fmt.Sprintf("[GET /skus/{identifier}/nodes][%d] getSkusIdentifierNodesOK  %+v", 200, o.Payload)
}

func (o *GetSkusIdentifierNodesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSkusIdentifierNodesNotFound creates a GetSkusIdentifierNodesNotFound with default headers values
func NewGetSkusIdentifierNodesNotFound() *GetSkusIdentifierNodesNotFound {
	return &GetSkusIdentifierNodesNotFound{}
}

/*GetSkusIdentifierNodesNotFound handles this case with default header values.

There is no sku with identifier.

*/
type GetSkusIdentifierNodesNotFound struct {
	Payload *models.Error
}

func (o *GetSkusIdentifierNodesNotFound) Error() string {
	return fmt.Sprintf("[GET /skus/{identifier}/nodes][%d] getSkusIdentifierNodesNotFound  %+v", 404, o.Payload)
}

func (o *GetSkusIdentifierNodesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSkusIdentifierNodesDefault creates a GetSkusIdentifierNodesDefault with default headers values
func NewGetSkusIdentifierNodesDefault(code int) *GetSkusIdentifierNodesDefault {
	return &GetSkusIdentifierNodesDefault{
		_statusCode: code,
	}
}

/*GetSkusIdentifierNodesDefault handles this case with default header values.

Unexpected error
*/
type GetSkusIdentifierNodesDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get skus identifier nodes default response
func (o *GetSkusIdentifierNodesDefault) Code() int {
	return o._statusCode
}

func (o *GetSkusIdentifierNodesDefault) Error() string {
	return fmt.Sprintf("[GET /skus/{identifier}/nodes][%d] GetSkusIdentifierNodes default  %+v", o._statusCode, o.Payload)
}

func (o *GetSkusIdentifierNodesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetSkusIdentifierNodesOKBodyBody get skus identifier nodes o k body body

swagger:model GetSkusIdentifierNodesOKBodyBody
*/
type GetSkusIdentifierNodesOKBodyBody interface{}
