package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/spiegela/gorackhd/models"
)

// NewNodesPutObmsByNodeIDParams creates a new NodesPutObmsByNodeIDParams object
// with the default values initialized.
func NewNodesPutObmsByNodeIDParams() *NodesPutObmsByNodeIDParams {
	var ()
	return &NodesPutObmsByNodeIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNodesPutObmsByNodeIDParamsWithTimeout creates a new NodesPutObmsByNodeIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNodesPutObmsByNodeIDParamsWithTimeout(timeout time.Duration) *NodesPutObmsByNodeIDParams {
	var ()
	return &NodesPutObmsByNodeIDParams{

		timeout: timeout,
	}
}

/*NodesPutObmsByNodeIDParams contains all the parameters to send to the API endpoint
for the nodes put obms by node Id operation typically these are written to a http.Request
*/
type NodesPutObmsByNodeIDParams struct {

	/*Body
	  The OBM settings information to create

	*/
	Body *models.NodesPostObmByID
	/*Identifier
	  The Node identifier

	*/
	Identifier string

	timeout time.Duration
}

// WithBody adds the body to the nodes put obms by node Id params
func (o *NodesPutObmsByNodeIDParams) WithBody(body *models.NodesPostObmByID) *NodesPutObmsByNodeIDParams {
	o.Body = body
	return o
}

// WithIdentifier adds the identifier to the nodes put obms by node Id params
func (o *NodesPutObmsByNodeIDParams) WithIdentifier(identifier string) *NodesPutObmsByNodeIDParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *NodesPutObmsByNodeIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.NodesPostObmByID)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
