package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/spiegela/gorackhd/models"
)

// NewNodesWorkflowActionByIDParams creates a new NodesWorkflowActionByIDParams object
// with the default values initialized.
func NewNodesWorkflowActionByIDParams() *NodesWorkflowActionByIDParams {
	var ()
	return &NodesWorkflowActionByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNodesWorkflowActionByIDParamsWithTimeout creates a new NodesWorkflowActionByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNodesWorkflowActionByIDParamsWithTimeout(timeout time.Duration) *NodesWorkflowActionByIDParams {
	var ()
	return &NodesWorkflowActionByIDParams{

		timeout: timeout,
	}
}

/*NodesWorkflowActionByIDParams contains all the parameters to send to the API endpoint
for the nodes workflow action by Id operation typically these are written to a http.Request
*/
type NodesWorkflowActionByIDParams struct {

	/*Action
	  The action property set to the command to execute

	*/
	Action *models.Action
	/*Identifier
	  The node identifier

	*/
	Identifier string

	timeout time.Duration
}

// WithAction adds the action to the nodes workflow action by Id params
func (o *NodesWorkflowActionByIDParams) WithAction(action *models.Action) *NodesWorkflowActionByIDParams {
	o.Action = action
	return o
}

// WithIdentifier adds the identifier to the nodes workflow action by Id params
func (o *NodesWorkflowActionByIDParams) WithIdentifier(identifier string) *NodesWorkflowActionByIDParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *NodesWorkflowActionByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Action == nil {
		o.Action = new(models.Action)
	}

	if err := r.SetBodyParam(o.Action); err != nil {
		return err
	}

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
