package nodes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewPatchNodesIdentifierParams creates a new PatchNodesIdentifierParams object
// with the default values initialized.
func NewPatchNodesIdentifierParams() *PatchNodesIdentifierParams {
	return &PatchNodesIdentifierParams{}
}

/*PatchNodesIdentifierParams contains all the parameters to send to the API endpoint
for the patch nodes identifier operation typically these are written to a http.Request
*/
type PatchNodesIdentifierParams struct {

	/*Body
	  object patches to apply.


	*/
	Body interface{}
	/*Identifier
	  Mac addresses and unique aliases to identify the node by, |
	expect a string or an array of strings.


	*/
	Identifier string
}

// WithBody adds the body to the patch nodes identifier params
func (o *PatchNodesIdentifierParams) WithBody(body interface{}) *PatchNodesIdentifierParams {
	o.Body = body
	return o
}

// WithIdentifier adds the identifier to the patch nodes identifier params
func (o *PatchNodesIdentifierParams) WithIdentifier(identifier string) *PatchNodesIdentifierParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PatchNodesIdentifierParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
