package delete

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/emccode/gorackhd/models"
)

// DeletePollersIdentifierReader is a Reader for the DeletePollersIdentifier structure.
type DeletePollersIdentifierReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeletePollersIdentifierReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeletePollersIdentifierNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeletePollersIdentifierNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewDeletePollersIdentifierDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewDeletePollersIdentifierNoContent creates a DeletePollersIdentifierNoContent with default headers values
func NewDeletePollersIdentifierNoContent() *DeletePollersIdentifierNoContent {
	return &DeletePollersIdentifierNoContent{}
}

/*DeletePollersIdentifierNoContent handles this case with default header values.

Poller delete successfully

*/
type DeletePollersIdentifierNoContent struct {
}

func (o *DeletePollersIdentifierNoContent) Error() string {
	return fmt.Sprintf("[DELETE /pollers/{identifier}][%d] deletePollersIdentifierNoContent ", 204)
}

func (o *DeletePollersIdentifierNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePollersIdentifierNotFound creates a DeletePollersIdentifierNotFound with default headers values
func NewDeletePollersIdentifierNotFound() *DeletePollersIdentifierNotFound {
	return &DeletePollersIdentifierNotFound{}
}

/*DeletePollersIdentifierNotFound handles this case with default header values.

There is no poller with specified identifier.

*/
type DeletePollersIdentifierNotFound struct {
	Payload *models.Error
}

func (o *DeletePollersIdentifierNotFound) Error() string {
	return fmt.Sprintf("[DELETE /pollers/{identifier}][%d] deletePollersIdentifierNotFound  %+v", 404, o.Payload)
}

func (o *DeletePollersIdentifierNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeletePollersIdentifierDefault creates a DeletePollersIdentifierDefault with default headers values
func NewDeletePollersIdentifierDefault(code int) *DeletePollersIdentifierDefault {
	return &DeletePollersIdentifierDefault{
		_statusCode: code,
	}
}

/*DeletePollersIdentifierDefault handles this case with default header values.

Unexpected error
*/
type DeletePollersIdentifierDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete pollers identifier default response
func (o *DeletePollersIdentifierDefault) Code() int {
	return o._statusCode
}

func (o *DeletePollersIdentifierDefault) Error() string {
	return fmt.Sprintf("[DELETE /pollers/{identifier}][%d] DeletePollersIdentifier default  %+v", o._statusCode, o.Payload)
}

func (o *DeletePollersIdentifierDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
