package delete

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteNodesIdentifierParams creates a new DeleteNodesIdentifierParams object
// with the default values initialized.
func NewDeleteNodesIdentifierParams() *DeleteNodesIdentifierParams {
	var ()
	return &DeleteNodesIdentifierParams{}
}

/*DeleteNodesIdentifierParams contains all the parameters to send to the API endpoint
for the delete nodes identifier operation typically these are written to a http.Request
*/
type DeleteNodesIdentifierParams struct {

	/*Identifier
	  Mac addresses and unique aliases to identify the node by, |
	expect a string or an array of strings.


	*/
	Identifier string
}

// WithIdentifier adds the identifier to the delete nodes identifier params
func (o *DeleteNodesIdentifierParams) WithIdentifier(Identifier string) *DeleteNodesIdentifierParams {
	o.Identifier = Identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteNodesIdentifierParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
