package templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/emccode/gorackhd/models"
)

type GetPollersIdentifierDataReader struct {
	formats strfmt.Registry
}

func (o *GetPollersIdentifierDataReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPollersIdentifierDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetPollersIdentifierDataNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetPollersIdentifierDataDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetPollersIdentifierDataOK creates a GetPollersIdentifierDataOK with default headers values
func NewGetPollersIdentifierDataOK() *GetPollersIdentifierDataOK {
	return &GetPollersIdentifierDataOK{}
}

/*GetPollersIdentifierDataOK

data for poller

*/
type GetPollersIdentifierDataOK struct {
	Payload GetPollersIdentifierDataOKBodyBody
}

func (o *GetPollersIdentifierDataOK) Error() string {
	return fmt.Sprintf("[GET /pollers/{identifier}/data][%d] getPollersIdentifierDataOK  %+v", 200, o.Payload)
}

func (o *GetPollersIdentifierDataOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil {
		return err
	}

	return nil
}

// NewGetPollersIdentifierDataNotFound creates a GetPollersIdentifierDataNotFound with default headers values
func NewGetPollersIdentifierDataNotFound() *GetPollersIdentifierDataNotFound {
	return &GetPollersIdentifierDataNotFound{}
}

/*GetPollersIdentifierDataNotFound

There is no poller with specified identifier.

*/
type GetPollersIdentifierDataNotFound struct {
	Payload *models.Error
}

func (o *GetPollersIdentifierDataNotFound) Error() string {
	return fmt.Sprintf("[GET /pollers/{identifier}/data][%d] getPollersIdentifierDataNotFound  %+v", 404, o.Payload)
}

func (o *GetPollersIdentifierDataNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewGetPollersIdentifierDataDefault creates a GetPollersIdentifierDataDefault with default headers values
func NewGetPollersIdentifierDataDefault(code int) *GetPollersIdentifierDataDefault {
	return &GetPollersIdentifierDataDefault{
		_statusCode: code,
	}
}

/*GetPollersIdentifierDataDefault

Unexpected error
*/
type GetPollersIdentifierDataDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get pollers identifier data default response
func (o *GetPollersIdentifierDataDefault) Code() int {
	return o._statusCode
}

func (o *GetPollersIdentifierDataDefault) Error() string {
	return fmt.Sprintf("[GET /pollers/{identifier}/data][%d] GetPollersIdentifierData default  %+v", o._statusCode, o.Payload)
}

func (o *GetPollersIdentifierDataDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

/*GetPollersIdentifierDataOKBodyBody GetPollersIdentifierDataOKBodyBody get pollers identifier data o k body body

swagger:model GetPollersIdentifierDataOKBodyBody
*/
type GetPollersIdentifierDataOKBodyBody interface{}
