package templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/codedellemc/gorackhd/models"
)

// GetTemplatesLibraryIdentifierReader is a Reader for the GetTemplatesLibraryIdentifier structure.
type GetTemplatesLibraryIdentifierReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetTemplatesLibraryIdentifierReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTemplatesLibraryIdentifierOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetTemplatesLibraryIdentifierNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetTemplatesLibraryIdentifierDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetTemplatesLibraryIdentifierOK creates a GetTemplatesLibraryIdentifierOK with default headers values
func NewGetTemplatesLibraryIdentifierOK() *GetTemplatesLibraryIdentifierOK {
	return &GetTemplatesLibraryIdentifierOK{}
}

/*GetTemplatesLibraryIdentifierOK handles this case with default header values.

single template

*/
type GetTemplatesLibraryIdentifierOK struct {
	Payload GetTemplatesLibraryIdentifierOKBodyBody
}

func (o *GetTemplatesLibraryIdentifierOK) Error() string {
	return fmt.Sprintf("[GET /templates/library/{identifier}][%d] getTemplatesLibraryIdentifierOK  %+v", 200, o.Payload)
}

func (o *GetTemplatesLibraryIdentifierOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTemplatesLibraryIdentifierNotFound creates a GetTemplatesLibraryIdentifierNotFound with default headers values
func NewGetTemplatesLibraryIdentifierNotFound() *GetTemplatesLibraryIdentifierNotFound {
	return &GetTemplatesLibraryIdentifierNotFound{}
}

/*GetTemplatesLibraryIdentifierNotFound handles this case with default header values.

There is no template with specified identifier.

*/
type GetTemplatesLibraryIdentifierNotFound struct {
	Payload *models.Error
}

func (o *GetTemplatesLibraryIdentifierNotFound) Error() string {
	return fmt.Sprintf("[GET /templates/library/{identifier}][%d] getTemplatesLibraryIdentifierNotFound  %+v", 404, o.Payload)
}

func (o *GetTemplatesLibraryIdentifierNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTemplatesLibraryIdentifierDefault creates a GetTemplatesLibraryIdentifierDefault with default headers values
func NewGetTemplatesLibraryIdentifierDefault(code int) *GetTemplatesLibraryIdentifierDefault {
	return &GetTemplatesLibraryIdentifierDefault{
		_statusCode: code,
	}
}

/*GetTemplatesLibraryIdentifierDefault handles this case with default header values.

Unexpected error
*/
type GetTemplatesLibraryIdentifierDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get templates library identifier default response
func (o *GetTemplatesLibraryIdentifierDefault) Code() int {
	return o._statusCode
}

func (o *GetTemplatesLibraryIdentifierDefault) Error() string {
	return fmt.Sprintf("[GET /templates/library/{identifier}][%d] GetTemplatesLibraryIdentifier default  %+v", o._statusCode, o.Payload)
}

func (o *GetTemplatesLibraryIdentifierDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetTemplatesLibraryIdentifierOKBodyBody get templates library identifier o k body body

swagger:model GetTemplatesLibraryIdentifierOKBodyBody
*/
type GetTemplatesLibraryIdentifierOKBodyBody interface{}
