package catalog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/strfmt"
)

// New creates a new catalog API client.
func New(transport client.Transport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for catalog API
*/
type Client struct {
	transport client.Transport
	formats   strfmt.Registry
}

/*get list of all catalogs


The catalogs endpoint returns json data that represent the catalogs of
all hardware in the system.

*/
func (a *Client) GetCatalogs(params *GetCatalogsParams) (*GetCatalogsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCatalogsParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:     "GetCatalogs",
		Params: params,
		Reader: &GetCatalogsReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetCatalogsOK), nil
}

/*get list of all catalogs


The catalogs endpoint returns json data that represent the catalogs of
all hardware in the system.

*/
func (a *Client) GetCatalogsIdentifier(params *GetCatalogsIdentifierParams) (*GetCatalogsIdentifierOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCatalogsIdentifierParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:     "GetCatalogsIdentifier",
		Params: params,
		Reader: &GetCatalogsIdentifierReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetCatalogsIdentifierOK), nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport client.Transport) {
	a.transport = transport
}

// NewAPIError creates a new API error
func NewAPIError(opName string, response interface{}, code int) APIError {
	return APIError{
		OperationName: opName,
		Response:      response,
		Code:          code,
	}
}

// APIError wraps an error model and captures the status code
type APIError struct {
	OperationName string
	Response      interface{}
	Code          int
}

func (a APIError) Error() string {
	return fmt.Sprintf("%s (status %d): %+v ", a.OperationName, a.Code, a.Response)
}
