package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/emccode/gorackhd/models"
)

type GetWorkflowsTasksReader struct {
	formats strfmt.Registry
}

func (o *GetWorkflowsTasksReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetWorkflowsTasksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetWorkflowsTasksDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetWorkflowsTasksOK creates a GetWorkflowsTasksOK with default headers values
func NewGetWorkflowsTasksOK() *GetWorkflowsTasksOK {
	return &GetWorkflowsTasksOK{}
}

/*GetWorkflowsTasksOK

Fetch tasks from task library

*/
type GetWorkflowsTasksOK struct {
	Payload GetWorkflowsTasksOKBodyBody
}

func (o *GetWorkflowsTasksOK) Error() string {
	return fmt.Sprintf("[GET /workflows/tasks][%d] getWorkflowsTasksOK  %+v", 200, o.Payload)
}

func (o *GetWorkflowsTasksOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil {
		return err
	}

	return nil
}

// NewGetWorkflowsTasksDefault creates a GetWorkflowsTasksDefault with default headers values
func NewGetWorkflowsTasksDefault(code int) *GetWorkflowsTasksDefault {
	return &GetWorkflowsTasksDefault{
		_statusCode: code,
	}
}

/*GetWorkflowsTasksDefault

Unexpected error
*/
type GetWorkflowsTasksDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get workflows tasks default response
func (o *GetWorkflowsTasksDefault) Code() int {
	return o._statusCode
}

func (o *GetWorkflowsTasksDefault) Error() string {
	return fmt.Sprintf("[GET /workflows/tasks][%d] GetWorkflowsTasks default  %+v", o._statusCode, o.Payload)
}

func (o *GetWorkflowsTasksDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

/*GetWorkflowsTasksOKBodyBody GetWorkflowsTasksOKBodyBody get workflows tasks o k body body

swagger:model GetWorkflowsTasksOKBodyBody
*/
type GetWorkflowsTasksOKBodyBody interface{}
