package pollers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeletePollersIdentifierParams creates a new DeletePollersIdentifierParams object
// with the default values initialized.
func NewDeletePollersIdentifierParams() *DeletePollersIdentifierParams {
	var ()
	return &DeletePollersIdentifierParams{}
}

/*DeletePollersIdentifierParams contains all the parameters to send to the API endpoint
for the delete pollers identifier operation typically these are written to a http.Request
*/
type DeletePollersIdentifierParams struct {

	/*Identifier
	  poller identifier


	*/
	Identifier string
}

// WithIdentifier adds the identifier to the delete pollers identifier params
func (o *DeletePollersIdentifierParams) WithIdentifier(Identifier string) *DeletePollersIdentifierParams {
	o.Identifier = Identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePollersIdentifierParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
