package obms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetObmsLibraryParams creates a new GetObmsLibraryParams object
// with the default values initialized.
func NewGetObmsLibraryParams() *GetObmsLibraryParams {

	return &GetObmsLibraryParams{}
}

/*GetObmsLibraryParams contains all the parameters to send to the API endpoint
for the get obms library operation typically these are written to a http.Request
*/
type GetObmsLibraryParams struct {
}

// WriteToRequest writes these params to a swagger request
func (o *GetObmsLibraryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
