package obms

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewObmsDeleteByIDParams creates a new ObmsDeleteByIDParams object
// with the default values initialized.
func NewObmsDeleteByIDParams() *ObmsDeleteByIDParams {
	var ()
	return &ObmsDeleteByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewObmsDeleteByIDParamsWithTimeout creates a new ObmsDeleteByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewObmsDeleteByIDParamsWithTimeout(timeout time.Duration) *ObmsDeleteByIDParams {
	var ()
	return &ObmsDeleteByIDParams{

		timeout: timeout,
	}
}

/*ObmsDeleteByIDParams contains all the parameters to send to the API endpoint
for the obms delete by Id operation typically these are written to a http.Request
*/
type ObmsDeleteByIDParams struct {

	/*Identifier
	  The OBM service identifier

	*/
	Identifier string

	timeout time.Duration
}

// WithIdentifier adds the identifier to the obms delete by Id params
func (o *ObmsDeleteByIDParams) WithIdentifier(identifier string) *ObmsDeleteByIDParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ObmsDeleteByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
