package profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/spiegela/gorackhd/models"
)

// NewProfilesPostSwitchErrorParams creates a new ProfilesPostSwitchErrorParams object
// with the default values initialized.
func NewProfilesPostSwitchErrorParams() *ProfilesPostSwitchErrorParams {
	var ()
	return &ProfilesPostSwitchErrorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProfilesPostSwitchErrorParamsWithTimeout creates a new ProfilesPostSwitchErrorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProfilesPostSwitchErrorParamsWithTimeout(timeout time.Duration) *ProfilesPostSwitchErrorParams {
	var ()
	return &ProfilesPostSwitchErrorParams{

		timeout: timeout,
	}
}

/*ProfilesPostSwitchErrorParams contains all the parameters to send to the API endpoint
for the profiles post switch error operation typically these are written to a http.Request
*/
type ProfilesPostSwitchErrorParams struct {

	/*Body
	  The switch error to send

	*/
	Body models.GenericObj

	timeout time.Duration
}

// WithBody adds the body to the profiles post switch error params
func (o *ProfilesPostSwitchErrorParams) WithBody(body models.GenericObj) *ProfilesPostSwitchErrorParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ProfilesPostSwitchErrorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
