package hooks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewHooksDelByIDParams creates a new HooksDelByIDParams object
// with the default values initialized.
func NewHooksDelByIDParams() *HooksDelByIDParams {
	var ()
	return &HooksDelByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHooksDelByIDParamsWithTimeout creates a new HooksDelByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHooksDelByIDParamsWithTimeout(timeout time.Duration) *HooksDelByIDParams {
	var ()
	return &HooksDelByIDParams{

		timeout: timeout,
	}
}

/*HooksDelByIDParams contains all the parameters to send to the API endpoint
for the hooks del by Id operation typically these are written to a http.Request
*/
type HooksDelByIDParams struct {

	/*Identifier
	  id of the hook you wish to delete

	*/
	Identifier string

	timeout time.Duration
}

// WithIdentifier adds the identifier to the hooks del by Id params
func (o *HooksDelByIDParams) WithIdentifier(identifier string) *HooksDelByIDParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *HooksDelByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
