package lookups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/emccode/gorackhd/models"
)

type PostLookupsIDReader struct {
	formats strfmt.Registry
}

func (o *PostLookupsIDReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostLookupsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostLookupsIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewPostLookupsIDOK creates a PostLookupsIDOK with default headers values
func NewPostLookupsIDOK() *PostLookupsIDOK {
	return &PostLookupsIDOK{}
}

/*PostLookupsIDOK

waterline response
*/
type PostLookupsIDOK struct {
	Payload PostLookupsIDOKBodyBody
}

func (o *PostLookupsIDOK) Error() string {
	return fmt.Sprintf("[POST /lookups/{id}][%d] postLookupsIdOK  %+v", 200, o.Payload)
}

func (o *PostLookupsIDOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil {
		return err
	}

	return nil
}

// NewPostLookupsIDDefault creates a PostLookupsIDDefault with default headers values
func NewPostLookupsIDDefault(code int) *PostLookupsIDDefault {
	return &PostLookupsIDDefault{
		_statusCode: code,
	}
}

/*PostLookupsIDDefault

Unexpected error
*/
type PostLookupsIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post lookups ID default response
func (o *PostLookupsIDDefault) Code() int {
	return o._statusCode
}

func (o *PostLookupsIDDefault) Error() string {
	return fmt.Sprintf("[POST /lookups/{id}][%d] PostLookupsID default  %+v", o._statusCode, o.Payload)
}

func (o *PostLookupsIDDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

/*PostLookupsIDOKBodyBody PostLookupsIDOKBodyBody post lookups ID o k body body

swagger:model PostLookupsIDOKBodyBody
*/
type PostLookupsIDOKBodyBody interface{}
