package post

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutFilesFileidentifierParams creates a new PutFilesFileidentifierParams object
// with the default values initialized.
func NewPutFilesFileidentifierParams() *PutFilesFileidentifierParams {
	var ()
	return &PutFilesFileidentifierParams{}
}

/*PutFilesFileidentifierParams contains all the parameters to send to the API endpoint
for the put files fileidentifier operation typically these are written to a http.Request
*/
type PutFilesFileidentifierParams struct {

	/*Fileidentifier
	  filename of the file you want to store

	*/
	Fileidentifier string
}

// WithFileidentifier adds the fileidentifier to the put files fileidentifier params
func (o *PutFilesFileidentifierParams) WithFileidentifier(Fileidentifier string) *PutFilesFileidentifierParams {
	o.Fileidentifier = Fileidentifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PutFilesFileidentifierParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param fileidentifier
	if err := r.SetPathParam("fileidentifier", o.Fileidentifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
