package put

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// NewPutWorkflowsParams creates a new PutWorkflowsParams object
// with the default values initialized.
func NewPutWorkflowsParams() *PutWorkflowsParams {
	return &PutWorkflowsParams{}
}

/*PutWorkflowsParams contains all the parameters to send to the API endpoint
for the put workflows operation typically these are written to a http.Request
*/
type PutWorkflowsParams struct {
}

// WriteToRequest writes these params to a swagger request
func (o *PutWorkflowsParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
