package workflows

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewWorkflowsGetByInstanceIDParams creates a new WorkflowsGetByInstanceIDParams object
// with the default values initialized.
func NewWorkflowsGetByInstanceIDParams() *WorkflowsGetByInstanceIDParams {
	var ()
	return &WorkflowsGetByInstanceIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewWorkflowsGetByInstanceIDParamsWithTimeout creates a new WorkflowsGetByInstanceIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewWorkflowsGetByInstanceIDParamsWithTimeout(timeout time.Duration) *WorkflowsGetByInstanceIDParams {
	var ()
	return &WorkflowsGetByInstanceIDParams{

		timeout: timeout,
	}
}

/*WorkflowsGetByInstanceIDParams contains all the parameters to send to the API endpoint
for the workflows get by instance Id operation typically these are written to a http.Request
*/
type WorkflowsGetByInstanceIDParams struct {

	/*Identifier
	  The workflow instance identifier

	*/
	Identifier string

	timeout time.Duration
}

// WithIdentifier adds the identifier to the workflows get by instance Id params
func (o *WorkflowsGetByInstanceIDParams) WithIdentifier(identifier string) *WorkflowsGetByInstanceIDParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *WorkflowsGetByInstanceIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
