package workflows

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/spiegela/gorackhd/models"
)

// WorkflowsGetReader is a Reader for the WorkflowsGet structure.
type WorkflowsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *WorkflowsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewWorkflowsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewWorkflowsGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewWorkflowsGetOK creates a WorkflowsGetOK with default headers values
func NewWorkflowsGetOK() *WorkflowsGetOK {
	return &WorkflowsGetOK{}
}

/*WorkflowsGetOK handles this case with default header values.

Successfully retrieved workflows
*/
type WorkflowsGetOK struct {
	Payload WorkflowsGetOKBodyBody
}

func (o *WorkflowsGetOK) Error() string {
	return fmt.Sprintf("[GET /workflows][%d] workflowsGetOK  %+v", 200, o.Payload)
}

func (o *WorkflowsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWorkflowsGetDefault creates a WorkflowsGetDefault with default headers values
func NewWorkflowsGetDefault(code int) *WorkflowsGetDefault {
	return &WorkflowsGetDefault{
		_statusCode: code,
	}
}

/*WorkflowsGetDefault handles this case with default header values.

Unexpected error
*/
type WorkflowsGetDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the workflows get default response
func (o *WorkflowsGetDefault) Code() int {
	return o._statusCode
}

func (o *WorkflowsGetDefault) Error() string {
	return fmt.Sprintf("[GET /workflows][%d] workflowsGet default  %+v", o._statusCode, o.Payload)
}

func (o *WorkflowsGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*WorkflowsGetOKBodyBody workflows get o k body body

swagger:model WorkflowsGetOKBodyBody
*/
type WorkflowsGetOKBodyBody interface{}
