package workflows

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewWorkflowsGetTasksByNameParams creates a new WorkflowsGetTasksByNameParams object
// with the default values initialized.
func NewWorkflowsGetTasksByNameParams() *WorkflowsGetTasksByNameParams {
	var ()
	return &WorkflowsGetTasksByNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewWorkflowsGetTasksByNameParamsWithTimeout creates a new WorkflowsGetTasksByNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewWorkflowsGetTasksByNameParamsWithTimeout(timeout time.Duration) *WorkflowsGetTasksByNameParams {
	var ()
	return &WorkflowsGetTasksByNameParams{

		timeout: timeout,
	}
}

/*WorkflowsGetTasksByNameParams contains all the parameters to send to the API endpoint
for the workflows get tasks by name operation typically these are written to a http.Request
*/
type WorkflowsGetTasksByNameParams struct {

	/*InjectableName
	  The task injectable name

	*/
	InjectableName string

	timeout time.Duration
}

// WithInjectableName adds the injectableName to the workflows get tasks by name params
func (o *WorkflowsGetTasksByNameParams) WithInjectableName(injectableName string) *WorkflowsGetTasksByNameParams {
	o.InjectableName = injectableName
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *WorkflowsGetTasksByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param injectableName
	if err := r.SetPathParam("injectableName", o.InjectableName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
