package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/spiegela/gorackhd/models"
)

// NewAddRoleParams creates a new AddRoleParams object
// with the default values initialized.
func NewAddRoleParams() *AddRoleParams {
	var ()
	return &AddRoleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddRoleParamsWithTimeout creates a new AddRoleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddRoleParamsWithTimeout(timeout time.Duration) *AddRoleParams {
	var ()
	return &AddRoleParams{

		timeout: timeout,
	}
}

/*AddRoleParams contains all the parameters to send to the API endpoint
for the add role operation typically these are written to a http.Request
*/
type AddRoleParams struct {

	/*Body
	  The role information

	*/
	Body *models.RoleObj

	timeout time.Duration
}

// WithBody adds the body to the add role params
func (o *AddRoleParams) WithBody(body *models.RoleObj) *AddRoleParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *AddRoleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.RoleObj)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
