package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTagParams creates a new GetTagParams object
// with the default values initialized.
func NewGetTagParams() *GetTagParams {
	var ()
	return &GetTagParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTagParamsWithTimeout creates a new GetTagParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTagParamsWithTimeout(timeout time.Duration) *GetTagParams {
	var ()
	return &GetTagParams{

		timeout: timeout,
	}
}

/*GetTagParams contains all the parameters to send to the API endpoint
for the get tag operation typically these are written to a http.Request
*/
type GetTagParams struct {

	/*TagName
	  The tag identifier

	*/
	TagName string

	timeout time.Duration
}

// WithTagName adds the tagName to the get tag params
func (o *GetTagParams) WithTagName(tagName string) *GetTagParams {
	o.TagName = tagName
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetTagParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param tagName
	if err := r.SetPathParam("tagName", o.TagName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
