package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLookupsGetByIDParams creates a new LookupsGetByIDParams object
// with the default values initialized.
func NewLookupsGetByIDParams() *LookupsGetByIDParams {
	var ()
	return &LookupsGetByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLookupsGetByIDParamsWithTimeout creates a new LookupsGetByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLookupsGetByIDParamsWithTimeout(timeout time.Duration) *LookupsGetByIDParams {
	var ()
	return &LookupsGetByIDParams{

		timeout: timeout,
	}
}

/*LookupsGetByIDParams contains all the parameters to send to the API endpoint
for the lookups get by Id operation typically these are written to a http.Request
*/
type LookupsGetByIDParams struct {

	/*ID
	  The lookup identifier

	*/
	ID string

	timeout time.Duration
}

// WithID adds the id to the lookups get by Id params
func (o *LookupsGetByIDParams) WithID(id string) *LookupsGetByIDParams {
	o.ID = id
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *LookupsGetByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
