package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/spiegela/gorackhd/models"
)

// NewModifyUserParams creates a new ModifyUserParams object
// with the default values initialized.
func NewModifyUserParams() *ModifyUserParams {
	var ()
	return &ModifyUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewModifyUserParamsWithTimeout creates a new ModifyUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewModifyUserParamsWithTimeout(timeout time.Duration) *ModifyUserParams {
	var ()
	return &ModifyUserParams{

		timeout: timeout,
	}
}

/*ModifyUserParams contains all the parameters to send to the API endpoint
for the modify user operation typically these are written to a http.Request
*/
type ModifyUserParams struct {

	/*Body
	  The user information

	*/
	Body *models.GetUserObj
	/*Name
	  The username

	*/
	Name string

	timeout time.Duration
}

// WithBody adds the body to the modify user params
func (o *ModifyUserParams) WithBody(body *models.GetUserObj) *ModifyUserParams {
	o.Body = body
	return o
}

// WithName adds the name to the modify user params
func (o *ModifyUserParams) WithName(name string) *ModifyUserParams {
	o.Name = name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ModifyUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Body == nil {
		o.Body = new(models.GetUserObj)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
