package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNodesGetCatalogSourceByIDParams creates a new NodesGetCatalogSourceByIDParams object
// with the default values initialized.
func NewNodesGetCatalogSourceByIDParams() *NodesGetCatalogSourceByIDParams {
	var ()
	return &NodesGetCatalogSourceByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNodesGetCatalogSourceByIDParamsWithTimeout creates a new NodesGetCatalogSourceByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNodesGetCatalogSourceByIDParamsWithTimeout(timeout time.Duration) *NodesGetCatalogSourceByIDParams {
	var ()
	return &NodesGetCatalogSourceByIDParams{

		timeout: timeout,
	}
}

/*NodesGetCatalogSourceByIDParams contains all the parameters to send to the API endpoint
for the nodes get catalog source by Id operation typically these are written to a http.Request
*/
type NodesGetCatalogSourceByIDParams struct {

	/*Identifier
	  The node identifier

	*/
	Identifier string
	/*Source
	  The source catalog name to fetch

	*/
	Source string

	timeout time.Duration
}

// WithIdentifier adds the identifier to the nodes get catalog source by Id params
func (o *NodesGetCatalogSourceByIDParams) WithIdentifier(identifier string) *NodesGetCatalogSourceByIDParams {
	o.Identifier = identifier
	return o
}

// WithSource adds the source to the nodes get catalog source by Id params
func (o *NodesGetCatalogSourceByIDParams) WithSource(source string) *NodesGetCatalogSourceByIDParams {
	o.Source = source
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *NodesGetCatalogSourceByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	// path param source
	if err := r.SetPathParam("source", o.Source); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
