package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewProfilesPutLibByNameParams creates a new ProfilesPutLibByNameParams object
// with the default values initialized.
func NewProfilesPutLibByNameParams() *ProfilesPutLibByNameParams {
	var ()
	return &ProfilesPutLibByNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewProfilesPutLibByNameParamsWithTimeout creates a new ProfilesPutLibByNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewProfilesPutLibByNameParamsWithTimeout(timeout time.Duration) *ProfilesPutLibByNameParams {
	var ()
	return &ProfilesPutLibByNameParams{

		timeout: timeout,
	}
}

/*ProfilesPutLibByNameParams contains all the parameters to send to the API endpoint
for the profiles put lib by name operation typically these are written to a http.Request
*/
type ProfilesPutLibByNameParams struct {

	/*Name
	  The profile name

	*/
	Name string
	/*Scope
	  The profile scope

	*/
	Scope *string

	timeout time.Duration
}

// WithName adds the name to the profiles put lib by name params
func (o *ProfilesPutLibByNameParams) WithName(name string) *ProfilesPutLibByNameParams {
	o.Name = name
	return o
}

// WithScope adds the scope to the profiles put lib by name params
func (o *ProfilesPutLibByNameParams) WithScope(scope *string) *ProfilesPutLibByNameParams {
	o.Scope = scope
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ProfilesPutLibByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.Scope != nil {

		// query param scope
		var qrScope string
		if o.Scope != nil {
			qrScope = *o.Scope
		}
		qScope := qrScope
		if qScope != "" {
			if err := r.SetQueryParam("scope", qScope); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
