package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSchemasIDGetParams creates a new SchemasIDGetParams object
// with the default values initialized.
func NewSchemasIDGetParams() *SchemasIDGetParams {
	var ()
	return &SchemasIDGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSchemasIDGetParamsWithTimeout creates a new SchemasIDGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSchemasIDGetParamsWithTimeout(timeout time.Duration) *SchemasIDGetParams {
	var ()
	return &SchemasIDGetParams{

		timeout: timeout,
	}
}

/*SchemasIDGetParams contains all the parameters to send to the API endpoint
for the schemas Id get operation typically these are written to a http.Request
*/
type SchemasIDGetParams struct {

	/*Identifier
	  The identifier of the schema

	*/
	Identifier string

	timeout time.Duration
}

// WithIdentifier adds the identifier to the schemas Id get params
func (o *SchemasIDGetParams) WithIdentifier(identifier string) *SchemasIDGetParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *SchemasIDGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
