package api_2_0

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewWorkflowsGetGraphsParams creates a new WorkflowsGetGraphsParams object
// with the default values initialized.
func NewWorkflowsGetGraphsParams() *WorkflowsGetGraphsParams {

	return &WorkflowsGetGraphsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewWorkflowsGetGraphsParamsWithTimeout creates a new WorkflowsGetGraphsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewWorkflowsGetGraphsParamsWithTimeout(timeout time.Duration) *WorkflowsGetGraphsParams {

	return &WorkflowsGetGraphsParams{

		timeout: timeout,
	}
}

/*WorkflowsGetGraphsParams contains all the parameters to send to the API endpoint
for the workflows get graphs operation typically these are written to a http.Request
*/
type WorkflowsGetGraphsParams struct {
	timeout time.Duration
}

// WriteToRequest writes these params to a swagger request
func (o *WorkflowsGetGraphsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
