// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
)

// FilesGetOKBody files get o k body
// swagger:model filesGetOKBody

type FilesGetOKBody *runtime.File
