package models

import "github.com/go-openapi/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Graphobject graphobject

swagger:model graphobject
*/
type Graphobject struct {

	/* context
	 */
	Context interface{} `json:"context,omitempty"`

	/* definition
	 */
	Definition interface{} `json:"definition,omitempty"`

	/* id
	 */
	ID string `json:"id,omitempty"`

	/* instanceid
	 */
	Instanceid string `json:"instanceid,omitempty"`

	/* node
	 */
	Node *Node `json:"node,omitempty"`

	/* tasks
	 */
	Tasks interface{} `json:"tasks,omitempty"`
}

// Validate validates this graphobject
func (m *Graphobject) Validate(formats strfmt.Registry) error {
	return nil
}
