package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*graphobject Graphobject graphobject

swagger:model graphobject
*/
type Graphobject struct {

	/* Context context
	 */
	Context interface{} `json:"context,omitempty"`

	/* Definition definition
	 */
	Definition interface{} `json:"definition,omitempty"`

	/* ID id
	 */
	ID *string `json:"id,omitempty"`

	/* Instanceid instanceid
	 */
	Instanceid *string `json:"instanceid,omitempty"`

	/* Node node
	 */
	Node *Node `json:"node,omitempty"`

	/* Tasks tasks
	 */
	Tasks interface{} `json:"tasks,omitempty"`
}

// Validate validates this graphobject
func (m *Graphobject) Validate(formats strfmt.Registry) error {
	return nil
}
