// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ObmLed obm led
// swagger:model obm_led

type ObmLed struct {

	// node Id
	NodeID string `json:"nodeId,omitempty"`

	// value
	Value bool `json:"value,omitempty"`
}

/* polymorph obm_led nodeId false */

/* polymorph obm_led value false */

// Validate validates this obm led
func (m *ObmLed) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ObmLed) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ObmLed) UnmarshalBinary(b []byte) error {
	var res ObmLed
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
