// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PostWorkflowOptions post workflow options
// swagger:model postWorkflowOptions

type PostWorkflowOptions struct {

	// defaults
	Defaults *PostWorkflowOptionsDefaults `json:"defaults,omitempty"`
}

/* polymorph postWorkflowOptions defaults false */

// Validate validates this post workflow options
func (m *PostWorkflowOptions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDefaults(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostWorkflowOptions) validateDefaults(formats strfmt.Registry) error {

	if swag.IsZero(m.Defaults) { // not required
		return nil
	}

	if m.Defaults != nil {

		if err := m.Defaults.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("defaults")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostWorkflowOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostWorkflowOptions) UnmarshalBinary(b []byte) error {
	var res PostWorkflowOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
