// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// WorkflowGraph workflow graph
// swagger:model workflow_graph

type WorkflowGraph struct {

	// friendly name
	FriendlyName string `json:"friendlyName,omitempty"`

	// injectable name
	InjectableName string `json:"injectableName,omitempty"`

	// options
	Options interface{} `json:"options,omitempty"`

	// tasks
	Tasks WorkflowGraphTasks `json:"tasks"`
}

/* polymorph workflow_graph friendlyName false */

/* polymorph workflow_graph injectableName false */

/* polymorph workflow_graph options false */

/* polymorph workflow_graph tasks false */

// Validate validates this workflow graph
func (m *WorkflowGraph) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *WorkflowGraph) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WorkflowGraph) UnmarshalBinary(b []byte) error {
	var res WorkflowGraph
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
