package skus

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/strfmt"

	"github.com/emccode/gorackhd/models"
)

type GetSkusIdentifierReader struct {
	formats strfmt.Registry
}

func (o *GetSkusIdentifierReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSkusIdentifierOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetSkusIdentifierNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetSkusIdentifierDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetSkusIdentifierOK creates a GetSkusIdentifierOK with default headers values
func NewGetSkusIdentifierOK() *GetSkusIdentifierOK {
	return &GetSkusIdentifierOK{}
}

/*GetSkusIdentifierOK

return sku

*/
type GetSkusIdentifierOK struct {
	Payload GetSkusIdentifierOKBodyBody
}

func (o *GetSkusIdentifierOK) Error() string {
	return fmt.Sprintf("[GET /skus/{identifier}][%d] getSkusIdentifierOK  %+v", 200, o.Payload)
}

func (o *GetSkusIdentifierOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil {
		return err
	}

	return nil
}

// NewGetSkusIdentifierNotFound creates a GetSkusIdentifierNotFound with default headers values
func NewGetSkusIdentifierNotFound() *GetSkusIdentifierNotFound {
	return &GetSkusIdentifierNotFound{}
}

/*GetSkusIdentifierNotFound

There is no sku with identifier.

*/
type GetSkusIdentifierNotFound struct {
	Payload *models.Error
}

func (o *GetSkusIdentifierNotFound) Error() string {
	return fmt.Sprintf("[GET /skus/{identifier}][%d] getSkusIdentifierNotFound  %+v", 404, o.Payload)
}

func (o *GetSkusIdentifierNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

// NewGetSkusIdentifierDefault creates a GetSkusIdentifierDefault with default headers values
func NewGetSkusIdentifierDefault(code int) *GetSkusIdentifierDefault {
	return &GetSkusIdentifierDefault{
		_statusCode: code,
	}
}

/*GetSkusIdentifierDefault

Unexpected error
*/
type GetSkusIdentifierDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get skus identifier default response
func (o *GetSkusIdentifierDefault) Code() int {
	return o._statusCode
}

func (o *GetSkusIdentifierDefault) Error() string {
	return fmt.Sprintf("[GET /skus/{identifier}][%d] GetSkusIdentifier default  %+v", o._statusCode, o.Payload)
}

func (o *GetSkusIdentifierDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil {
		return err
	}

	return nil
}

/*GetSkusIdentifierOKBodyBody GetSkusIdentifierOKBodyBody get skus identifier o k body body

swagger:model GetSkusIdentifierOKBodyBody
*/
type GetSkusIdentifierOKBodyBody interface{}
